name: React Native CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      date_today: 2025-02-13
      repository_name: ReactNative-GitHub-Action

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17  # Updated to Java 17

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set Android SDK
        uses: android-actions/setup-android@v2

      - name: Make Gradle executable
        run: chmod +x ./android/gradlew

      - name: Run tests
        run: npm test

      - name: Build Android app
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Build Android AAB
        run: |
          cd android
          ./gradlew bundleRelease

      - name: Upload AAB as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-bundle
          path: android/app/build/outputs/bundle/release/app-release.aab

      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: app-release-${{ env.repository_name }}-${{ env.date_today }}
          path: android/app/build/outputs/apk/release/app-release.apk
          retention-days: 1

      - name: Upload AAB Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: app-release-bundle-${{ env.repository_name }}-${{ env.date_today }}
          path: android/app/build/outputs/bundle/release/app-release.aab
          retention-days: 1